In [2]:
import pandas as pd
import numpy as np
df=pd.read_excel("/content/solar_energy_usage_indian_states.xlsx")
df.head()

,State,Average Solar Radiation (kWh/m²/day),Installed Solar Capacity (MW),Predicted Usage (GWh/year),Population (Millions)
0,Andhra Pradesh,6.24,5781,11751,82.3
1,Arunachal Pradesh,4.56,5366,7826,104.8
2,Assam,4.86,4604,5764,51.6
3,Bihar,6.29,852,25802,161.2
4,Chhattisgarh,5.20,9036,7509,96.1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   State                                 30 non-null     object
 1   Average Solar Radiation (kWh/m²/day)  30 non-null     float64
 2   Installed Solar Capacity (MW)         30 non-null     int64
 3   Predicted Usage (GWh/year)            30 non-null     int64
 4   Population (Millions)                 30 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 1.3+ KB

In [4]:
df.describe()

,Average Solar Radiation (kWh/m²/day),Installed Solar Capacity (MW),Predicted Usage (GWh/year),Population (Millions)
count,30.000000,30.000000,30.000000,30.000000
mean,5.351333,5229.400000,23259.900000,108.050000
std,0.688044,2816.639556,13174.231987,60.753713
min,4.030000,852.000000,3948.000000,4.000000
25%,4.972500,2692.500000,10894.500000,52.225000
50%,5.325000,5432.000000,25098.000000,108.000000
75%,5.905000,7777.500000,34077.250000,160.200000
max,6.480000,9554.000000,46765.000000,198.800000

In [5]:
df['State'].unique()

array(['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
       'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh',
       'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland',
       'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal', 'Delhi', 'Jammu and Kashmir'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['State'] = label_encoder.fit_transform(df['State'])

In [7]:
df.head()

,State,Average Solar Radiation (kWh/m²/day),Installed Solar Capacity (MW),Predicted Usage (GWh/year),Population (Millions)
0,0,6.24,5781,11751,82.3
1,1,4.56,5366,7826,104.8
2,2,4.86,4604,5764,51.6
3,3,6.29,852,25802,161.2
4,4,5.20,9036,7509,96.1

In [8]:
df["Predicted Usage (GWh/year)"].sum()

np.int64(697797)

In [9]:
df["Predicted Usage (GWh/year)"].mean()

np.float64(23259.9)

In [10]:
from sklearn.model_selection import train_test_split
x = df.drop(columns=["Predicted Usage (GWh/year)"])
y = df["Predicted Usage (GWh/year)"]

In [11]:
x

,State,Average Solar Radiation (kWh/m²/day),Installed Solar Capacity (MW),Population (Millions)
0,0,6.24,5781,82.3
1,1,4.56,5366,104.8
2,2,4.86,4604,51.6
3,3,6.29,852,161.2
4,4,5.20,9036,96.1
5,6,5.69,5019,189.2
6,7,4.11,8126,54.1
7,8,4.60,1432,36.9
8,9,4.61,9554,43.2
9,11,5.37,9104,23.3
10,12,5.70,5498,156.1
11,13,6.19,1384,4.0
12,14,5.77,1874,180.2
13,15,5.28,7857,104.2
14,16,6.22,1312,198.8
15,17,4.96,7076,124.4
16,18,5.22,2105,160.5
17,19,5.95,9155,111.2
18,20,6.48,3122,151.1
19,21,6.18,5599,186.6
20,22,5.11,4311,159.3
21,23,4.03,2757,118.0
22,24,5.66,8099,32.4
23,25,5.01,2671,25.8
24,26,5.96,8974,94.0
25,27,5.38,2920,34.9
26,28,5.46,7539,186.9
27,29,5.13,6214,117.2
28,5,5.27,2558,193.2
29,10,4.05,6983,60.0

In [12]:
y

0     11751
1      7826
2      5764
3     25802
4      7509
5     13440
6     21472
7     12749
8     36123
9     21941
10    33721
11     4920
12    34196
13    10609
14    25384
15    35335
16    35274
17    29181
18    33323
19    30584
20    24812
21    10358
22    40238
23    33283
24    12472
25    35262
26     3948
27    46765
28    46177
29     7578
Name: Predicted Usage (GWh/year), dtype: int64

In [13]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [15]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(xtrain, ytrain)

LinearRegression()

In [16]:
ypred = model.predict(xtest)

In [17]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(ytest, ypred)
mse = mean_squared_error(ytest, ypred)
r2 = r2_score(ytest, ypred)

# Print results
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("R-squared Score:", r2)

Mean Absolute Error: 17388.232998732765
Mean Squared Error: 346159348.94205123
R-squared Score: -5.143437713683995